### ISSUE TITLE
AICommander has unused method isNearPlayer()

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#150]
And it does not use the List<> interface

**Comment by 0-Gixty-0** [comment]
That's because I used it in previous versions of the AICommander code and then decided to integrate it into another method. However, I left it there since it is a good method that could be used later and didn't want to scrap the code. Will in future be moved to some form of utility, repurposed, or removed.

**Comment by willayy** [comment]
I'm pretty sure having unused code lying around in production is bad practice. Found this StackOverflow article that explains it quite well https://stackoverflow.com/questions/15699995/could-someone-explain-the-pros-of-deleting-or-keeping-unused-code

**Comment by 0-Gixty-0** [comment]
I repurposed this method when completing #131 to detect when an enemy is in a certain radius to an entity.
