### ISSUE TITLE
Necessary Addition To Pom File For Compiling The Code

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#157]
I had to add the following lines to the pom file in order for the code to compile:
```
<properties>
        <maven.compiler.source>20</maven.compiler.source>
        <maven.compiler.target>20</maven.compiler.target>
</properties>
``` 

I'm not sure what changes have been made but when I pulled the main branch today I could not compile without this addition. Are we sure the pom file is correctly configured? May be related to change https://github.com/0-Gixty-0/Grupp-11-OOPP/commit/068d0959deaad92f9dccb90c17de6591d807db5f and 1d2ccb2e06153daba8be55f3797398c9b67c1971

**Comment by willayy** [comment]
Strange, compiles fine for me without it, probably development environment related since we use the same OS.
```
<properties>
        <maven.compiler.source>20</maven.compiler.source>
        <maven.compiler.target>20</maven.compiler.target>
</properties>
```
This is just telling the compiler to use Java 20 to compile and run the application. 

I removed the properties before because it was set to Java 1.8 which I thought was a weird ChatGPT artifact or something. But other than that I'm pretty confident the POM file isn't configured incorrectly.
Leaving it up to you to close this @0-Gixty-0

**Comment by willayy** [comment]
Ok this addition made it impossible for me to compile the code since I'm using JDK 17 since Java is backwardscompatible im going to push it down to 17.
