### ISSUE TITLE
US-109: Reduce SailingGameApplication coupling

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#225]
#### Original issue
---
SalingGameApplication is dependent on multiple concrete implementations of AStandardPanel. This breaks the dependency inversion principle and is harmful to the codebase. Currently the AStandardPanel class contains no methods and only two font attributes. I also see that two classes GameOverPanel and MainMenuPanel use buttons to some capacity. Maybe this functionality can be defined in an interface InteractablePanel? Nevertheless, I think it would benefit the code to find some common functionality or settings and define them in the AStandardPanel, at the very least as abstract methods. Therefore, AStandardPanel would have a reason to exist and SailingGameApplication can depend on it instead of the concrete classes. 

#### US
As a developer i want to decrease coupling between application and view.

### Because
Making code low coupling increases robustnes.

### Tasks
- [x] Make the application communicate with the view only through the AppFrame class.

### Acceptance criteria
This US is done when there is low coupling between view and application

**Comment by willayy** [comment]
Yes i kind of agree👍

AStandardPanel exists because the inheriting classes all share this code. Classes dont need methods to have a purpose.

'''Java
Dimension size = new Dimension(width, height);
        this.setPreferredSize(size);
        this.setMaximumSize(size);
        this.setBackground(Color.GRAY);
        this.bigFont = new Font("Arial", Font.PLAIN, 50);
        this.smallFont = new Font("Arial", Font.PLAIN, 20);
'''

I dont think we need more abstraction here. The major problem is high coupling, this can be fixed by adding  the Standardpanels directly to the AppFrame and not add them through the application. The SailingGameApplication can then use the methods which are now in AApplication to interact with key components of the view. SailingGameApplication can depend on AppFrame since both are high level components.

Will probably be able to fix this tomorrow.

**Comment by 0-Gixty-0** [comment]
Fair, what I meant was that it was worth looking into if there is any common functionality that can be refactored into the AStandardPanel. However, I think that your plan sounds like a good idea.

**Comment by willayy** [comment]
I Turned this issue post into a user story
