### ISSUE TITLE
IMovableEntityFactory should be an abstract class

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#71]
### Because
* If you ever want to make another EntityFactory this code will probably be needed (as an inherited protected method)
https://github.com/0-Gixty-0/Grupp-11-OOPP/blob/a1cfa89fa2313c79eeac8a94bda6b3e6a648c062/sailinggame/src/main/java/com/group11/model/StandardMovableEntityFactory.java#L31-L46
* IMovableEntityFactory is only going to be implemented by (Something)MovableEntityFactory classes so if there aren't any other classes that should be able to have this api i think an abstract class makes more sense.

**Comment by 0-Gixty-0** [comment]
I disagree with this for multiple reasons. As I stated in my pull request and my original issue this code was meant to be more fleshed out than it’s current state. This is because a lot of the methods and functions I thought were implemented were not. For example UnmovableEntity and default constructors. I’m also thinking of refactoring the whole thing to a builder pattern. Also of note, a simple factory does not require an abstract class and in this case the referenced method was simply a quick snippet to make it easier to make the dimensions. In reality it may be a parameter passed to the factory along with a position. As stated in the pull request I merged the code and closed the issue despite all these issues since it doesn’t affect anything and gives us information on how this user story should be implemented more than just in text.

I’m closing the issue for these reasons and those stated in the original issue and pull request.

**Comment by willayy** [comment]
All good! I'm just looking at the code in main as production code so I didn't understand it was subject to change. My reasoning was that method looked like something that belonged in a superclass because it looked like it should be used by all EntityFactories.
